# Generated by Django 4.1.1 on 2023-05-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenterapp', '0002_category_parent_category_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
