# Generated by Django 4.1.1 on 2023-05-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenterapp', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
