# Generated by Django 4.1.1 on 2023-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenterapp', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.BooleanField(default=False),
        ),
    ]
