# Generated by Django 4.1.1 on 2023-05-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenterapp', '0005_category_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
    ]
